name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Java Version
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
     
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.0"
          channel: "stable"

      - name: Install dependencies
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build release APK
        run: flutter build apk

      - name: Build release Bundle
        run: flutter build appbundle
